// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunymvHe7wX9vSBDN0XGk6n1OgDwCKP3Y',
    appId: '1:714842411456:web:810be731cdd5a85345f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    authDomain: 'mobilityplus-74105.firebaseapp.com',
    databaseURL: 'https://mobilityplus-74105-default-rtdb.firebaseio.com',
    storageBucket: 'mobilityplus-74105.firebasestorage.app',
    measurementId: 'G-1RJK414WTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuZ47B67_Es0vDaakG_tooRyi2cFaU38',
    appId: '1:714842411456:android:00654aeadabf40be45f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    databaseURL: 'https://mobilityplus-74105-default-rtdb.firebaseio.com',
    storageBucket: 'mobilityplus-74105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI5fO6bUpaNX7grZox6SBAuLFhhhycB_k',
    appId: '1:714842411456:ios:610a42643b7e316245f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    databaseURL: 'https://mobilityplus-74105-default-rtdb.firebaseio.com',
    storageBucket: 'mobilityplus-74105.firebasestorage.app',
    androidClientId: '714842411456-0rgr81no2dhi10kml13pljsv68jisr9r.apps.googleusercontent.com',
    iosClientId: '714842411456-813nel2oujo2limgnn11pqbqgnghbo23.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilitydashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI5fO6bUpaNX7grZox6SBAuLFhhhycB_k',
    appId: '1:714842411456:ios:610a42643b7e316245f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    databaseURL: 'https://mobilityplus-74105-default-rtdb.firebaseio.com',
    storageBucket: 'mobilityplus-74105.firebasestorage.app',
    androidClientId: '714842411456-0rgr81no2dhi10kml13pljsv68jisr9r.apps.googleusercontent.com',
    iosClientId: '714842411456-813nel2oujo2limgnn11pqbqgnghbo23.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilitydashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwL2F1cmYwk985tMStplg6iarBODY_I18',
    appId: '1:714842411456:web:ece9486296c2c60c45f825',
    messagingSenderId: '714842411456',
    projectId: 'mobilityplus-74105',
    authDomain: 'mobilityplus-74105.firebaseapp.com',
    databaseURL: 'https://mobilityplus-74105-default-rtdb.firebaseio.com',
    storageBucket: 'mobilityplus-74105.firebasestorage.app',
    measurementId: 'G-L3PWFVL6KS',
  );
}
